version: 2
linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 54
    gocyclo:
      min-complexity: 25
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    mnd:
      ignored-numbers:
        - "2"
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    rules:
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - mnd
          - revive
          - staticcheck
          - thelper
        path: .*test.*.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/calyptia/)
    gofumpt:
      extra-rules: false
  exclusions:
    generated: lax
    paths:
      - custom/custom.go
      - input/input.go
      - output/output.go
      - third_party$
      - builtin$
      - examples/*
